name: {{ projectName.snakeCase() }}
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  get_it: ^7.6.4
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  kt_dart: ^1.1.0
  logging: ^1.2.0
  universal_io: ^2.2.2
  intl: ^0.18.1
  multiple_result: ^5.1.0
  sized_context: ^1.0.0+4
  gap: ^3.0.1
{{#useDio}}  dio: ^5.0.1
  path: ^1.8.2 # every version of flutter_test from sdk depends on path 1.8.2
  http_parser: ^4.0.2{{/useDio}}

{{#useFirebase}}  # Firebase
  firebase_core: ^2.17.0
  firebase_crashlytics: ^3.3.7
  firebase_analytics: ^10.5.1{{/useFirebase}}

  # UI
  auto_localized: ^1.3.3
  flutter_svg: ^2.0.7
  flutter_svg_provider: ^1.0.6
  extended_image: ^8.1.1
  flutter_native_splash: ^2.3.3

  # Services
  shared_preferences: ^2.2.1
  package_info_plus: ^5.0.0
  path_provider: ^2.1.1
{{#useHive}}  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0{{/useHive}}
{{#useJson}}  json_annotation: ^4.8.1{{/useJson}}

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3 # build_runner >=2.4.0 which requires SDK version >=3.0.0-134.0.dev <4.0.0
  freezed: ^2.4.3
{{#useHive}}  hive_generator: ^2.0.1{{/useHive}}
{{#useJson}}  json_serializable: ^6.7.1{{/useJson}}
  auto_localized_generator: ^1.3.3
  flutter_lints: ^2.0.3
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  image_path_android: "resources/app_icon/app_icon.png"
  adaptive_icon_background: "#4F62ED"
  adaptive_icon_foreground: "resources/app_icon/app_icon_adaptive.png"
  image_path_ios: "resources/app_icon/app_icon.png"
  remove_alpha_ios: true

# dart run flutter_native_splash:create
# dart run flutter_native_splash:remove
flutter_native_splash:
  color: "#F6F6F6"
# Spider used to generate asset fields
# spider create
# spider build --watch
