name: {{ projectName.snakeCase() }}
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  get_it: ^8.0.0
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  kt_dart: ^1.1.0
  logging: ^1.3.0
  flutter_logcat_monitor: ^1.0.2
  universal_io: ^2.2.2
  intl: ^0.19.0
  multiple_result: ^5.1.0
  sized_context: ^1.0.0+4
  gap: ^3.0.1
{{#useDio}}  dio: ^5.7.0
  path: ^1.9.0
  http_parser: ^4.0.2{{/useDio}}

{{#useFirebase}}  # Firebase
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  firebase_analytics: ^11.3.3{{/useFirebase}}

  # UI
  auto_localized: ^1.3.3
  flutter_svg: ^2.0.10+1
  flutter_svg_provider: ^1.0.7
  extended_image: ^9.0.4
  flutter_native_splash: ^2.4.2
  cupertino_icons: ^1.0.6

  # Services
  shared_preferences: ^2.3.2
  package_info_plus: ^8.1.0
  path_provider: ^2.1.4
  uuid: ^4.5.1
{{#useHive}}  flutter_secure_storage: ^9.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0{{/useHive}}
{{#useJson}}  json_annotation: ^4.9.0{{/useJson}}

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.13
  freezed: ^2.5.7
{{#useHive}}  hive_generator: ^2.0.1{{/useHive}}
{{#useJson}}  json_serializable: ^6.8.0{{/useJson}}
  auto_localized_generator: ^1.3.3
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "resources/app_icon/app_icon.png"
  adaptive_icon_background: "resources/app_icon/app_icon_adaptive.png"
  adaptive_icon_foreground: "resources/app_icon/app_icon_adaptive.png"
  image_path_ios: "resources/app_icon/app_icon.png"
  remove_alpha_ios: true

# dart run flutter_native_splash:create
# dart run flutter_native_splash:remove
flutter_native_splash:
  color: "#F6F6F6"
# Spider used to generate asset fields
# spider create
# spider build --watch
